root -b -l -q 'Draw.C("SubGeV-elike-0dcy")'
root -b -l -q 'Draw.C("SubGeV-elike-1dcy")'
root -b -l -q 'Draw.C("SubGeV-mulike-0dcy")'
root -b -l -q 'Draw.C("SubGeV-mulike-1dcy")'
root -b -l -q 'Draw.C("SubGeV-mulike-2dcy")'
